### ISSUE TITLE
Cart rule name should be unique.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1279]
- Framework Version: 0.1.6

-----------------------------------------------

![Screenshot (1)](https://user-images.githubusercontent.com/45203177/62864168-9fde5380-bd28-11e9-8fe0-27d4ad33e9cc.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

----------------------------------------
Not Fixed

![Screenshot (67)](https://user-images.githubusercontent.com/45203177/63427350-8dec6700-c432-11e9-889f-2deea48a95b9.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------

Fixed
