### ISSUE TITLE
Getting exception while creating cart rules if any of the dropdown field left blank.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1288]
- Framework Version: 0.1.6

--------------------------------------------

![Screenshot (15)](https://user-images.githubusercontent.com/45203177/62940525-69b8d680-bdf1-11e9-8222-d88ff9da1f47.png)
![Screenshot from 2019-08-13 15-30-04](https://user-images.githubusercontent.com/45203177/62940555-79381f80-bdf1-11e9-9082-602d6e7b11dc.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Not fixed

![Screenshot from 2019-08-21 15-48-29](https://user-images.githubusercontent.com/45203177/63424244-a016d700-c42b-11e9-80ee-1d58b2b71f9b.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Not Fixed

![Screenshot from 2019-09-07 12-24-59](https://user-images.githubusercontent.com/45203177/64471128-aa92d980-d16a-11e9-84eb-c052f4a0d632.png)

**Comment by prashant-webkul** [comment]
Wait till merge of #1445
