### ISSUE TITLE
Change filter conditions according to numeric for priority column in Inventory Sources 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1306]
![Screenshot from 2019-08-16 17-46-26](https://user-images.githubusercontent.com/52821836/63167167-14c5cc00-c04e-11e9-9107-09b3e16231d4.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------------------

Not fixed

![Screenshot from 2019-09-07 15-14-13](https://user-images.githubusercontent.com/45203177/64472858-39f7b700-d182-11e9-8f8a-c82a2a92afbf.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------------

Fixed

![Screenshot from 2019-09-07 16-00-44](https://user-images.githubusercontent.com/45203177/64473779-c6a57380-d188-11e9-9326-4d6743ba8289.png)
