### ISSUE TITLE
Getting exception when click on Apply rules if conditions are left empty while creating catalog rule.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1319]
- Framework Version: 0.1.6

--------------------------------------------

![Screenshot (35)](https://user-images.githubusercontent.com/45203177/63324449-bba7b200-c345-11e9-8c84-ab004a0dd254.png)
![Screenshot from 2019-08-20 12-20-27](https://user-images.githubusercontent.com/45203177/63324468-c4988380-c345-11e9-9a17-1ec6ebb22b8b.png)

**Comment by prashant-webkul** [comment]
Fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------
 Not Fixed

![Screenshot from 2019-08-21 12-12-47](https://user-images.githubusercontent.com/45203177/63408623-1821d480-c40d-11e9-89c2-de07d2ad8f9a.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------
Fixed
