### ISSUE TITLE
Tax is not added on product at checkout.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#146]
Framework Version: 0.1.1

Test Step:
1. Created a tax rate.
2. Added this tax rate in a tax category.
3. Used this tax category while creating a product.
4. Placed order for this product. Zip code used in shipping address is same as used in range for tax rate.

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version: 0.1.2

**Comment by plakhin** [comment]
Tax is still not being added.

Framework Version: 0.1.5

Test Step:

Created a tax rate.
Added this tax rate in a tax category.
Used this tax category while creating a product.
Placed order for this product. Zip code used in shipping address is same as used in range for tax rate.

**Comment by rahulshukla-webkul** [comment]
Hi @plakhin 

Can you attach screenshots of all step so that we can check more effectively. 

Thanks
Rahul Shukla
