### ISSUE TITLE
Cart rule not working with Cart Item Attribute "weight".

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1849]
# Bug report

### Title
Cart rule not working with Cart Item Attribute "weight".
### Issue Description
Cart rule not working with Cart Item Attribute "weight".
### Preconditions

    1. Commit id.-567419a534dbe0dc16866124090e73f90e9e5f85

### Steps to reproduce

    1. step1- Create a cart rule with specific coupon and in condition select weight.
    2. step2- Use this created coupon on checkout.

### Expected result
Coupon should get applied

### Actual result

Getting error message "coupon code is invalid"

![Screenshot from 2019-12-05 12-18-14](https://user-images.githubusercontent.com/45203177/70210705-5b544900-1759-11ea-937e-95f84935d826.png)

![Screenshot from 2019-12-05 12-17-49](https://user-images.githubusercontent.com/45203177/70210711-6018fd00-1759-11ea-816b-ef78ca467fae.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.9

-------------------------------------

Fixed
![Screenshot from 2019-12-20 16-33-02](https://user-images.githubusercontent.com/45203177/71250732-68bb2700-2346-11ea-9e90-2bf43eee1dc9.png)

![Screenshot from 2019-12-20 16-32-21](https://user-images.githubusercontent.com/45203177/71250714-5c36ce80-2346-11ea-8a7e-c6400313e5e8.png)

**Comment by inimist** [comment]
Cart rules are not working at all. It worked for the very first rule I created yesterday but not now. I have created/recreated rules and products but still not able to make it work.  Have cleared all types of cache several times but nothing is working.

**Comment by jyoti-webkul** [comment]
@inimist 
Which version of bagisto you are using?
