### ISSUE TITLE
Wrong price of product in case of multiple exchange rates.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2226]
# Bug report

### Title
Wrong price of product in case of multiple exchange rates.
### Issue Description
I have create three currency and their exchange rates its working fine for first two currencies, but for third currency it calculates wrong amount.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- For usd save exchange rate 1.
    2. step2- Create other currency and exchange rate for it.
    3.step3- Create one more currency and exchange rate for this.

### Expected result
For third currency calculated exchange rate is wrong.
### Actual result
Exchange rate should be calculated correctly.

![Screenshot (47)](https://user-images.githubusercontent.com/45203177/73594082-c3909280-4530-11ea-8006-7ff335229d6e.png)

![Screenshot (48)](https://user-images.githubusercontent.com/45203177/73594087-cab7a080-4530-11ea-889d-4d367fbb855c.png)

![Screenshot (49)](https://user-images.githubusercontent.com/45203177/73594091-d1461800-4530-11ea-86c3-8e51f6b25024.png)

**Comment by adavie1** [comment]
Is this the same issue as #2139?

**Comment by rahulshukla-webkul** [comment]
Hi @adavie1 

It has the same issue and thanks for your solution.

**Comment by jyoti-webkul** [comment]
- Fixed

---------------------------

![Screenshot from 2020-02-05 15-35-33](https://user-images.githubusercontent.com/45203177/73831968-436a7580-482d-11ea-860e-edd991f09a87.png)

![Screenshot from 2020-02-05 15-35-42](https://user-images.githubusercontent.com/45203177/73831983-48c7c000-482d-11ea-9006-fd50ad4459d4.png)

![Screenshot from 2020-02-05 15-35-53](https://user-images.githubusercontent.com/45203177/73831993-4d8c7400-482d-11ea-92ae-3ff1a3682c9b.png)

![Screenshot from 2020-02-05 15-36-05](https://user-images.githubusercontent.com/45203177/73832001-53825500-482d-11ea-9b4a-497f38acd30d.png)

**Comment by adavie1** [comment]
![image](https://user-images.githubusercontent.com/3030402/74080528-dbf83400-4a7f-11ea-9a61-752fa105c473.png)

Still getting an error in the calculations  on the invoices though.

The price should be MYR474.22
