### ISSUE TITLE
causing error when run php artisan route:list

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2770]
# Bug report

causing error when run php artisan route:list

### Preconditions

    1. framework Version- master
    2. PHP version- 7.4

### Actual result

I get the following error:
In ResourceController.php line 47:
Trying to access array offset on value of type null

**Comment by jitendra-webkul** [comment]
Can not reproduce this issue. I am closing this issue for now, feel free to reopen if needed.

**Comment by richmondnursery** [comment]
@jitendra-webkul 
I think the bug is still there.
In my installation, I get the same error. I have to comment out line 47 in: packages/Webkul/API/Http/Controllers/Shop/ResourceController.php:
`$this->repository = app($this->_config['repository']);`
When that is commented out, php artisan route:list works. 
In my install, it appears $this->_config is set to null on construct. Perhaps check for null in this line is appropriate?

**Comment by nikhilbhatia22** [comment]
The issue still persists in v1.2.0
![image](https://user-images.githubusercontent.com/12022338/100076031-bdc0c080-2e66-11eb-8a73-72e6948668f0.png)

**Comment by vaishaliwebkul** [comment]
@nikhilbhatia22 @richmondnursery 
the bug does not exist in the master branch & already resolved with this PR https://github.com/bagisto/bagisto/pull/4185
Kindly check again by updating files on the mentioned PR.

**Comment by nikhilbhatia22** [comment]
Unfortunately, the issue still persists. Probably, it has been though updated in the `master` branch, but it does not seem to have been pushed to `bagisto-standard` repository, which is what is being used when installing bagisto through composer as per bagisto docs.

### Steps to reproduce
1. `composer create-project bagisto/bagisto-standard`
2. `php artisan route:list`

**Comment by myowinthein** [comment]
I'm using Bagisto v.1.2.0 & that issues still exists. Please do some quick patch.

To locate the issue, just install Bagisto with `composer create-project bagisto/bagisto-standard` command & run `php artisan route:list`.
