### ISSUE TITLE
Customer pays order in PayPal but there is no record in bagisto

### ISSUE THREAD

**Issue by dan3460** [bagisto/bagisto#2931]
# Bug report

### Title
Customer pays order in PayPal but there is no record in bagisto

### Issue Description
twice has happened and with two different customers that they go through the order process and they are able to get to PayPal and pay for the order, but there is no record in Bagisto.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. V1.1.1
    2. don't know
    3. Running Ubuntu 16.04.6

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

Don't know

**Comment by rahulcs0082** [comment]
Hi @dan3460 

Did you check the Sales (orders) section from admin login as we are showing all order-related data there?
If yes then can tell which kind of record or data need to capture for PayPal.

**Comment by dan3460** [comment]
I looked at the orders and it was not there. I was able to get the detail from Paypal so we could complete the orders. I look directly on the database and the customers are not in the customer table.
![Capture1](https://user-images.githubusercontent.com/34137788/80367095-76cf0600-8858-11ea-99fb-5a9692e60381.PNG)
i search the orders this customer has, and the only one showing is one that he paid in cash 10 days before.
![Capture2](https://user-images.githubusercontent.com/34137788/80367987-01fccb80-885a-11ea-9f1e-8d6fd10a2058.PNG)

**Comment by rahulcs0082** [comment]
Hi @dan3460 

You can open this order and can find all its related data along with the payment method. - https://prnt.sc/s7tzxl  and https://prnt.sc/s7u0t4.

**Comment by dan3460** [comment]
I think we are talking pass each other. The PayPal order **IS NOT** on the Bagisto data base. I cannot open the order to find all related data. The order is not there. Today i have another customer that placed the order on PayPal and the order is not there. He said that he filled out the registration but is not there. He place the order and the only confirmation that he got was from PayPal.

**Comment by vaishaliwebkul** [comment]
@dan3460 
Try by Upgrading the bagisto version 1.1.2.

**Comment by vaishaliwebkul** [comment]
@dan3460 
Hope your issue is resolved.

Feel free to reopen it anytime.

**Comment by MattApril** [comment]
**This is not fixed. I just had this same bug happen to my customer as well. I am using v1.1.2 - This is a very serious bug and needs attention.**

The bug I am getting is "Trying to get property 'grand_total' of non-object" in Webkul\Paypal\Helpers\Ipn::processOrder.
