### ISSUE TITLE
Images can not add on velocity theme

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#3020]
<img width="1440" alt="Screenshot 2020-05-07 at 7 11 37 PM" src="https://user-images.githubusercontent.com/24676063/81323984-9525d480-9096-11ea-9d1c-efeac8099394.png">

**Comment by vaishaliwebkul** [comment]
Hi @irisda 
It's a broken image issue, please follow this guide https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions

**Comment by kduqi** [comment]
![image](https://user-images.githubusercontent.com/13215092/81476258-39338b00-9211-11ea-8e31-b6b5fc6238eb.png)
hi @vaishaliwebkul, this is the error I get only when adding single image like categories or velocity images

**Comment by zakybaraq** [comment]
Try to change your `APP_URL` in `.env` file in root directory just like this `http://localhost:8000` and then try type this command `php artisan storage:link`

**Comment by kduqi** [comment]
I checked the APP_URL and it is set to `http://localhost:8000`. The storage was already linked but I deleted and linked it again. It still shows the same thing.

**Comment by vaishaliwebkul** [comment]
@kduqi 
Could you please tell us about the bagisto version?

**Comment by zakybaraq** [comment]
Before doing anything, you should do this magic command, just type `php artisan config:clear` and `php artisan cache:clear`

**Comment by kduqi** [comment]
I tried `php artisan config:clear` and `php artisan cache:clear` but still is the same. I have the latest changes from master branch. This issue started after I got this change:
https://github.com/bagisto/bagisto/pull/3010

It is only for images that are single like `category images`  or `velocity template images`. On products it works fine.

**Comment by vaishaliwebkul** [comment]
@kduqi @irisda 
Thanks for notifying the bug.
It's fixed now, please check.

**Comment by vaishaliwebkul** [comment]
I hope your issue is resolved now. Feel free to reopen the issue.

**Comment by SIMONNABUKO** [comment]
This issue still persists. Product images are showing but the logo and banner images arent showing. Now I Deleted storage directory in the public folder then ran PHP artisan storage: link and it worked on the localhost. However, when I uploaded the project to the shared hosting, the images are broken again. Kindly help. This is the project URL showing broken banner images and logos: https://sirerics.co.ke/
