### ISSUE TITLE
[Critical] Onecheckout preventing to continue to shipping method after selecting address

### ISSUE THREAD

**Issue by chemisax** [bagisto/bagisto#3032]
# Bug report

### Bug
In onecheckout page, request to `checkout/save-address` fails sometimes. 

### Issue Description
In onecheckout page, request to `checkout/save-address` fails sometimes. It prevents the user to continue selecting the shipping method/payment method, thus preventing placing an order.

### Preconditions
1. Bagisto version: latest at time of writing
2. At least one address must be saved in the user account

### Steps to reproduce
    1. Go to one checkout
    2. Select saved address
    3. If flows continues to shipping method, reload
    4. Select saved address
    5. Request fails

### Expected result
The address should be saved and continue to the next step. (Shipping method)

Heres a video showing the issue: https://www.dropbox.com/s/1r5mk6e6az7nb86/bagisto%20error.mov?dl=0

Error log:
```
local.ERROR: Trying to get property 'id' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object at packages/Webkul/Shipping/src/Shipping.php:85)
```

### Actual result

- Request to save-address fails
- Selected address gets saved 3 times
- Flow does not continue to shipping method

**I think this bug is critical because it can prevent users from placing an order and abandoning the site.**

Thank you.

**Comment by vaishaliwebkul** [comment]
@chemisax
Thanks for notifying the bug.
Bug is already solved in master branch https://github.com/bagisto/bagisto/issues/2987 please update the code.

**Comment by chemisax** [comment]
@vaishaliwebkul 

Thank you, I've updated from master several days ago so it might be a delay.

Thank you.

**Comment by yosirn** [comment]
I've just install a fresh app but still having the same issue
![Screenshot from 2020-05-17 17-31-40](https://user-images.githubusercontent.com/10193377/82155448-927c6980-9864-11ea-8116-f6fedadd1c28.png)

**Comment by arooba499** [comment]
@vaishaliwebkul can you tell me how you fixed this bug as i am almost done with my project and i made alot of changes in core so update code is not possible for me ..please waiting for your response

**Comment by vaishaliwebkul** [comment]
Hi @arooba499 
In this case, you can update the files as mention in this pull request https://github.com/bagisto/bagisto/pull/3008

Thanks
