### ISSUE TITLE
Bagisto not show images cache gallery with google cloud storage

### ISSUE THREAD

**Issue by raulidavid** [bagisto/bagisto#3285]
https://github.com/bagisto/bagisto/issues/2009

I wish solve cache show images with gsc how to??? please

**Comment by devansh-webkul** [comment]
Hi @raulidavid,

Apology for the late response. Are you still facing this issue? If not then let me know.

**Comment by devansh-webkul** [comment]
I am closing this as it's a very old issue. May be user resolved at his end. Feel free to raise the issue if you facing any of them.

**Comment by mikeyapina** [comment]
Th
![Uploading Screen Shot 2022-01-25 at 11.00.52 PM.png…]()
is issue is not solved as there are files and issues that make nose sense as they do not exist and it seems like the vendor would understand what to do there. The problem set is easy -- the s3 URLs are not being used and the 
<img width="1622" alt="Screen Shot 2022-01-25 at 11 34 51 PM" src="https://user-images.githubusercontent.com/18667035/151110011-d4a0639f-2fec-40ee-b14d-4e4f25a0e07f.png">
local variable when you set them in the env to be used. IN my case are going the images are being uploaded property but never retrieved they are only going to the local system URL and also the filename is properly being set in the database that is being uploaded and deleted properly in s3.
