### ISSUE TITLE
Sale level is displaying even if special price date has been already expired 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3411]
# Bug report

### Title
Sale level is displaying even if special price date has been already expired 

### Issue Description
if special price from and to both has already expired still sale level is coming on product

### Preconditions

    1. framework Version. Master

### Steps to reproduce

    1. step1 - give special price in product 
    2. step2 - select  date as - https://prnt.sc/tawhob

### Expected result
sale level should not be there 
### Actual result
![Screenshot (27)](https://user-images.githubusercontent.com/52821836/86436450-eb726500-bd1f-11ea-90a0-37dba44c4903.png)

**Comment by bhanu-webkul** [comment]
Fixed in Master

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
still getting the same issue in master https://prnt.sc/tta3bi

**Comment by vaishaliwebkul** [comment]
fixed
