### ISSUE TITLE
Problem with the compare page as a guest and as a customer

### ISSUE THREAD

**Issue by CesarMdz** [bagisto/bagisto#3452]
v. 1.1.2

I have problems when comparing products, since in guest mode and client mode, if only one product is added, the table is displayed poorly.
<a href="https://ibb.co/61D6CMd"><img src="https://i.ibb.co/nnQhJGW/2.png" alt="2" border="0"></a>

When I log in with a customer account and click on compare products, some products do not add them, although the message that they were added appears, that does not happen as a guest, only as a customer.

<a href="https://ibb.co/2cBk3TJ"><img src="https://i.ibb.co/QYGKv40/3.png" alt="3" border="0"></a>

And as a client, the compare page does not show the name of the product or the description, if I am invited, this data does, but not as a client.

<a href="https://ibb.co/qYKpFfD"><img src="https://i.ibb.co/m5k4FwR/1.png" alt="1" border="0"></a>

Thanks for your attention

**Comment by vaishaliwebkul** [comment]
Hi @CesarMdz 
Thanks for pointing out the issues.

1st bug & 3rd bug-> It's resolved in the master branch
You can check these fixed bug here https://github.com/bagisto/bagisto/issues/3172

2nd bug-> We will Fix this soon

**Comment by CesarMdz** [comment]
Hi, thanks for your response

**Comment by CesarMdz** [comment]
Well, I already made the changes they mention but the problem of bug 1 & 3 still continues or I don't know if something additional needs to be done to the changes shown in the issue #3172

**Comment by CesarMdz** [comment]
**

**New bug!**

** 
In the mobile version when products are added and clicked to go to the compare page, the button does not respond and redirects to the main page, only when 3 or 4 clicks on the compare button shows you the compare page

**Comment by vaishaliwebkul** [comment]
@CesarMdz 
Kindly take a pull from the [master branch](https://github.com/bagisto/bagisto/tree/master), there is all the mention above 3 points are resolved.

Feel free to reopen this issue if it is still not resolved,
