### ISSUE TITLE
Possibility to order infinite configurable products (product_ordered_inventories and / or order_items not correctly updated at order)

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto#5451]
# Bug Report

## Issue Description
Currently it is possible to order an infinite amount of configurable products as the product_ordered_inventories table / order_items table are not filled correctly on order

## Bagisto Version
master branch and online demo using v1.3.3

## Steps To Reproduce
In demo admin
- create configurable product with differenze sizes (s,m,l...)
- set quantity of all to 1
- set individually visible of configurable product to true and to false for the simple variants

In demo shop
- go to configurable product and add 1 of size s to cart
- order cart
- size s should not be available anymore
- go to configurable product

## Actual Result
- it is still possible to add 1 of size s, even though the available amount should be 0

## Expected Result
- it should not be possible to add 1 of size s

## Possible Explanation
Above happens using master branch as well.
- Locally on master branch we observe that after order the order_items table seems incorrect. For the scenario described above we have two items in there:
  - The configurable product with qty_ordered 1
  - Its simple variant which was ordered with qty_ordered 0
- Then https://github.com/bagisto/bagisto/blob/65e70b6c6dbbfc987a2b28d4fc8def7c60c63249/packages/Webkul/Sales/src/Repositories/OrderItemRepository.php#L102 copies the quantity of the simple variant (0) to product_ordered_inventories
- So the net totalQuantity for the simple product does not change

**Comment by derMart** [comment]
it seems this is already problematic in the cart_items table. There, also the quantity for the respective configurable product is 1, but the quantity for the simple variant which is actually in the cart is 0. If there are two different variants for the same configurable products in the cart, then there are two copies of the configurable product (actually with the counts in the cart as quantity) and for each copy there is a simple product (the variant) with count 0

**Comment by devansh-webkul** [comment]
Hi @derMart,

Thanks for reporting this. I will check and fix this.

**Comment by devansh-webkul** [comment]
Hi @derMart,

I just added quantity to the child one. Let me know are you still facing issue,
https://github.com/bagisto/bagisto/pull/5454

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this issue **is fixed**. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6553293?key=4a97f5ca898bb38de6203e0b378f0215).

**Comment by derMart** [comment]
@devansh-webkul Thanks alot! Works when adding items to cart. Issue remaining is updating the cart. In https://github.com/bagisto/bagisto/blob/837f78fa287fa078d46edb057e3cd45c43b0cdc8/packages/Webkul/Checkout/src/Cart.php#L293 only quantity of configurable is updated, not that of the child.

**Comment by derMart** [comment]
another bug, now if I order e.g. 3 times the variant of size s, product_ordered_inventories has quantity 9 instead of 3

**Comment by derMart** [comment]
also `returnQtyToProductInventory` probably has to be updated, I do see code like `($orderItem->qty_ordered / $orderItem->parent->qty_ordered) * $shipmentItem->qty` in there which could be problematic if not parent and child have same quantity (?)

**Comment by devansh-webkul** [comment]
> Another issue: If I order e.g. 3 times the variant of size s, product_ordered_inventories has quantity 9 instead of 3 EDIT: the simple variant in order_items also has quantity 9, in that scenario EDIT2: See
> 
> https://github.com/bagisto/bagisto/blob/837f78fa287fa078d46edb057e3cd45c43b0cdc8/packages/Webkul/Checkout/src/Cart.php#L751
> 
> @devansh-webkul Have you thought about (unit) tests for these kind of things? This should eliminate alot of problems and would improve finding regressions in the future for all those cases found already and detects side effects of changes

We tested this with multiple quantities also and everythings seems fine even we checked with cart, order and invoices also. Not facing this.

Becuase i have changed in the configurable portion not everywhere.

If possible can you provide us PR what you trying to say so that i can verify.

**Comment by devansh-webkul** [comment]
Okay got the point. Seems like its getting doubled.

**Comment by devansh-webkul** [comment]
I will check all possible cases and if you find anything then let me know. Thanks for reporting this.

**Comment by devansh-webkul** [comment]
Reverted previous PR.

And by putting this,

~~~php
$child['quantity'] = $child['quantity'] ? $child['quantity'] * $data['quantity'] : $data['quantity'];
~~~

Instead of this,

~~~php
$child['quantity'] = $child['quantity'] ? $child['quantity'] * $data['quantity'] : $child['quantity'];
~~~

Solving most of the problems. But still i will check all the possible cases for the parent one.

I will take some time on this and will prepare the unit and functional also for this.

**Comment by devansh-webkul** [comment]
@derMart,

Sorry for the delay but currently I am busy with some other task, but I have kept in mind this also. That's why I am simplifying test cases for this also.

I will provide you with the fix in the next release. If you want to contribute you can provide us with the pull request. We will consider it if everything is fine.

**Comment by derMart** [comment]
> I will provide you with the fix in the next release. If you want to contribute you can provide us with the pull request. We will consider it if everything is fine.

I am sorry, in this case I do not have the time resources to do that.

**Comment by devansh-webkul** [comment]
No worry I will check. Low priority I added for my understanding I will start working on them once I get free.

**Comment by devansh-webkul** [comment]
Hi @derMart,

The mentioned issue has been fixed.

And for unit tests, configurable products and bundle products both support need to be added. Will provide it later.

And let me know, if still any inventory impacted.

**Comment by devansh-webkul** [comment]
Hi @derMart,

Are you still facing any issues?

**Comment by derMart** [comment]
@devansh-webkul well not yet directly related to order quantities as in this bug report, but a related bug is here: https://github.com/bagisto/bagisto/issues/6290

What is the status of the unit tests? Please I see that unit tests for this core functionality have low priority and are not yet done in two months. This is really concerning. Please take this seriously. Unit tests are very important and should have high priority!
