### ISSUE TITLE
 The admin should be able to delete the users.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6196]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Login as an admin.
**2.** Click on the users inside the settings.
**3.** Try to delete any user.

**Expected result:** The admin should be able to delete the users.
**Actual result:** The admin is not able to delete the users. Please find the screen [Here](https://www.awesomescreenshot.com/video/8162674?key=7cc5a0bcfa4abf75773e4dddfaa5cb9d).

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul  and @jitendra-webkul,

Fixed from this commit,
https://github.com/bagisto/bagisto/pull/6223/commits/c40e4066d22040ef6f3ac947f46f7ccd8f5b43dd

Pull request is in the testing phase.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Not fixed.** still **getting** the **same** **issue**.
Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8237594?key=f520e5d074d41e51e26797cf12014829).

**Comment by devansh-webkul** [comment]
Please try with a hard refresh. This is working fine.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
Now, this issue **is fixed.** Please find the screenshot [Here](https://prnt.sc/qqTghrymbiZl).
