### ISSUE TITLE
Not able to save tax configuration

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8157]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Not able to save tax configuration

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'configuration section'
2. Scroll down to 'tax section
3. Click on catalog
4. Fill details and try to save
5. See an error

### Expected Result

Should be able to save the configuration

### Actual Result

Not able to save the configuration

### Screenshots

https://prnt.sc/rh1biDzdAUeK

**Comment by amit-webkul** [comment]
Fixed

**Comment by Amitk-webkul** [comment]
The issue is still there. [Here](https://prnt.sc/HtjV5puswu2z)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/M8lfdOHDztwt), for future reference.
