### ISSUE TITLE
Configuration is not updating

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8159]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Rich Snippets Configuration is not updating

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'configuration section'
2. Click on 'rich snippets
3. Change any toggle.
4. Save the configuration.
5. See an error

### Expected Result

Configuration should be changed after update.

### Actual Result

Configuration is not updating all toggle is checked.

**Comment by jitendra-webkul** [comment]
Fixed in #8201

**Comment by Amitk-webkul** [comment]
The issue is still there. [Here](https://prnt.sc/kQHy8bvz9XsJ)

**Comment by amit-webkul** [comment]
Fixed in this [PR](https://github.com/bagisto/bagisto/pull/8296)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/9AfCkkq5EQO5), for future reference.
