### ISSUE TITLE
Slug is not updating. it is taking previous slug.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8228]
### Terms

- [X] #8232

### Bagisto Version(s) affected

master

### Issue Description

While creating/updating the title it is showing the slug is updating but actually not updating the slug it took the previous slug.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one created product.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit product' inside the Catalog/products
3. Change the product name
4. See the error

### Expected Result

It should be updated the slug according to the current value.

### Actual Result

It takes the previous slug. [Here](https://prnt.sc/G7mZrWdjUNbG)

**Comment by Amitk-webkul** [comment]
The issue is still there. [Here](https://prnt.sc/SPFd2gZZtSRR)

**Comment by suraj-webkul** [comment]
Its working fine.
Please try to run development envirnment server then try again.

**Comment by Amitk-webkul** [comment]
@suraj-webkul While entering the name it is highlighted the required fields. [Here](https://prnt.sc/DdVBOymWlxTe)

**Comment by suraj-webkul** [comment]
Fixed

**Comment by Amitk-webkul** [comment]
@suraj-webkul Still facing the same issue. [Here](https://prnt.sc/o2qd8Qd5_qiK)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/vvpHpkrqxQhA), for future reference.
