### ISSUE TITLE
Logo isn't display on mobile/tablet menu; On devices >768px logo is displayed correctly

### ISSUE THREAD

**Issue by CatalinRobert** [bagisto/bagisto#9340]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0

### Issue Description

After adding an image logo, on desktop all looks good but when I switch to tablet or mobile version the velocity logo displays instead the newly one.

### Preconditions

Bagisto 2.0;
I forked the project. (synced).

### Steps to reproduce

1. Go to 'Settings->Channel.'
2. Click on 'Add logo'
3. Scroll down to 'Menu''
4. Logo doesn t exist on mobile

### Expected Result

I put a screenshot.

### Actual Result

See screenshot

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/47644093/fa289ab1-ea3f-433b-a3dc-4657d306265a)

**Comment by shivendra-webkul** [comment]
Hii @CatalinRobert The reported issue has been resolved in our master branch Please take the latest pull. Grateful for your collaboration!
Result :- 
![logo issue](https://github.com/bagisto/bagisto/assets/121868701/53f66667-320c-4bd2-a662-3654323dc58b)

**Comment by ashishkumar-webkul** [comment]
@CatalinRobert 

Thank you so much for your contribution and we really appretiate it, we would like to inform you that the following issue has been fixed in master branch. You can take the latest code from there, Please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/e5162276-42af-4d95-a6bf-60030b41a326

For latest code you can follow the link [here](https://github.com/bagisto/bagisto)

**Comment by CatalinRobert** [comment]
Hello, 
Sorry for my delay. The thing is the project is forked ( is synced ) and a similar issue still persists(the one with creating/deleting carousels). I mean... I already have the latest code from bagisto/bagisto and I cannot create/delete carousels.  Thank you! One more thing... you're doing a great job taking care of bagisto. Cheers to you all!
