### ISSUE TITLE
Autodetect browser language

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#953]
The Locale middleware should include autodetection of browser language, if included in the available languages.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------

Fixed

**Comment by stefano73it** [comment]
How has this been fixed? It doesn't work on my setup, it should detect Italian language, but still showing English.
