### ISSUE TITLE
Unable to Checkout Product  when Address is created from user profile and then proceed for checkout. Email is a mandatory field at checkout.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9537]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.1

### Issue Description

Created a user and then added addresses from the customer profile. There when we create a user address email is not required.
After that add a product to cart and there we can see that the addresses which we have saved are appearing. After selecting the address when we click the proceed button there we can see in console errors are appearing and we are unable to process the checkout.

### Preconditions

1. Create a User.
2. Add addresses to the user, minimum 2.

### Steps to reproduce

1. Go to User Profile -> Create Addresses -> There we can see that the email details are not appearing.
2. Add any product to cart -> Proceed with checkout.
3. Select the address which is pre-saved -> Click Proceed button.
4. See errors in console -> 422 (Unprocessable Content)
5. Unable to checkout.

### Expected Result

Case 1.

If Email is mandartory field in Checkout page, then it should be added when we are creating user address.

Case 2.

If creating address from user email is not present, then it should not be a mandatory field at checkout page.

### Actual Result

Currently we are unable to proceed with checkout as address is created from user end and email is a mandatory field. We need to add email and then can checkout product.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/a4405734-166c-4e51-9d3e-17c7e4d1d240

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed. Email is mandatory at the User end Address create end.
Please find the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/51ed7a01-e67e-4946-9943-1f11f9c8fe47

**Comment by shaizy1234** [comment]
Hello, Issue is still there even your demo page is still not working, I also tried your latest upload but still same isue.

**Comment by shivendra-webkul** [comment]
Hi @shaizy1234, Thank you for addressing the email issue. We've already fixed this in the Master branch, and it's now functioning correctly. Please ensure you have the latest code from the Master branch. I've attached the pull request related to this issue for your reference. Kindly incorporate the outlined changes into your codebase.
PR link-https://github.com/bagisto/bagisto/pull/9555

~ The checkout page is functioning properly for both guest users and registered users without any issues. Please review the attached video for verification. Let us know if you have any further questions or concerns. Thank you!"
Video- https://webkul.chatwhizz.com/share/view-recording/65e55319095e20057950ff7d
